"""Allow Bulwark (and other configured parents) to iframe OpenCloud, Element, and Kanidm login.

Writes kit integration sidecars:
- OpenCloud: .opencloud-easy-deploy/integration/embed.yaml
- Matrix: .matrix-easy-deploy/integration/embed.yaml
- Kanidm: .kanidm-easy-deploy/integration/embed.yaml

Element's login navigates the webmail iframe to Kanidm. After sign-in, Element
also opens Kanidm in a nested iframe (silent session refresh). Kanidm's sidecar
therefore lists both the webmail parent and the app origins in between.
OpenCloud and Matrix sidecars list only the webmail parent. Kits merge those
files on apply. Operators can add extra origins in each kit's deploy.yaml
(`embed.frame_ancestors`) or opt out with `embed.managed: false`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from scripts.oidc_wire import (
    read_matrix_domain,
    read_matrix_element_domain,
    read_opencloud_domain,
    read_webmail_domain,
    resolve_kit_path,
    write_sidecar,
)

EMBED_SIDECAR_HEADER = (
    "# Generated by easydeploy-engine. Re-apply the engine after domain changes.\n"
    "# Set embed.managed: false on the kit to ignore this file.\n"
)

PLACEHOLDER_HOSTS = frozenset(
    {
        "webmail.example.com",
        "example.com",
        "mail.example.com",
    }
)

KIT_EMBED_SIDECARS = (
    ("opencloud", ".opencloud-easy-deploy/integration/embed.yaml"),
    ("matrix", ".matrix-easy-deploy/integration/embed.yaml"),
    ("kanidm", ".kanidm-easy-deploy/integration/embed.yaml"),
)


def https_origin(value: Any) -> str:
    """Normalize a hostname or URL to `https://host` with no trailing slash."""
    text = str(value or "").strip()
    if not text:
        return ""
    if "://" in text:
        scheme, rest = text.split("://", 1)
        if scheme.lower() not in {"http", "https"}:
            return ""
        host = rest.split("/")[0].split("?")[0].split("#")[0].strip().lower()
    else:
        host = text.split("/")[0].split("?")[0].split("#")[0].strip().lower()
        if host.startswith("*."):
            host = host[2:]
    if not host or host in PLACEHOLDER_HOSTS:
        return ""
    return f"https://{host}"


def unique_https_origins(values: Any) -> list[str]:
    origins: list[str] = []
    seen: set[str] = set()
    if values is None:
        return origins
    if isinstance(values, str):
        values = [values]
    if not isinstance(values, list):
        return origins
    for item in values:
        origin = https_origin(item)
        if origin and origin not in seen:
            seen.add(origin)
            origins.append(origin)
    return origins


def collect_embed_parents(engine_config: dict, enabled: list[dict], project_root: Path) -> list[str]:
    """Parents allowed to iframe OpenCloud/Element (Bulwark webmail, plus extras)."""
    raw: list[Any] = []
    embed = engine_config.get("embed") or {}
    if isinstance(embed, dict):
        raw.extend(embed.get("frame_ancestors") or [])

    by_name = {item["name"]: item for item in enabled}
    identity = engine_config.get("identity") or {}
    consumers = identity.get("consumers") or {}
    if not isinstance(consumers, dict):
        consumers = {}
    stalwart_cfg = consumers.get("stalwart") or {}
    if not isinstance(stalwart_cfg, dict):
        stalwart_cfg = {}

    webmail = str(stalwart_cfg.get("webmail") or stalwart_cfg.get("webmail_domain") or "").strip()
    stalwart = by_name.get("stalwart")
    if stalwart:
        kit_root = resolve_kit_path(stalwart, project_root)
        webmail = webmail or read_webmail_domain(kit_root)
    if webmail:
        raw.append(webmail)

    return unique_https_origins(raw)


def _consumer_domain(engine_config: dict, consumer: str, key: str) -> str:
    identity = engine_config.get("identity") or {}
    consumers = identity.get("consumers") if isinstance(identity, dict) else {}
    if not isinstance(consumers, dict):
        return ""
    entry = consumers.get(consumer) or {}
    if not isinstance(entry, dict):
        return ""
    return str(entry.get(key) or "").strip()


def collect_nested_app_origins(engine_config: dict, enabled: list[dict], project_root: Path) -> list[str]:
    """App origins that sit between webmail and Kanidm during OIDC silent refresh."""
    raw: list[Any] = []
    by_name = {item["name"]: item for item in enabled}

    opencloud_domain = _consumer_domain(engine_config, "opencloud", "domain")
    if not opencloud_domain and (opencloud := by_name.get("opencloud")):
        try:
            opencloud_domain = read_opencloud_domain(resolve_kit_path(opencloud, project_root))
        except (OSError, ValueError):
            opencloud_domain = ""
    if opencloud_domain:
        raw.append(opencloud_domain)

    matrix_domain = _consumer_domain(engine_config, "matrix", "domain")
    element_domain = _consumer_domain(engine_config, "matrix", "element_domain")
    matrix = by_name.get("matrix")
    if matrix:
        kit_root = resolve_kit_path(matrix, project_root)
        if not matrix_domain:
            try:
                matrix_domain = read_matrix_domain(kit_root)
            except (OSError, ValueError):
                matrix_domain = ""
        if matrix_domain and not element_domain:
            element_domain = read_matrix_element_domain(kit_root, matrix_domain)
    if matrix_domain:
        raw.append(matrix_domain)
    if element_domain:
        raw.append(element_domain)
    return unique_https_origins(raw)


def wire_embed(
    engine_config: dict,
    enabled: list[dict],
    project_root: Path,
) -> list[str]:
    """Write embed sidecars so apps can be iframed by Bulwark. Returns status lines."""
    parents = collect_embed_parents(engine_config, enabled, project_root)
    # Silent OIDC refresh loads Kanidm inside the app, which is itself inside
    # webmail. frame-ancestors checks every ancestor, so both must be listed.
    kanidm_origins = unique_https_origins(
        [*parents, *collect_nested_app_origins(engine_config, enabled, project_root)]
    )
    by_name = {item["name"]: item for item in enabled}
    notes: list[str] = []
    written = 0

    for name, relpath in KIT_EMBED_SIDECARS:
        service = by_name.get(name)
        if not service:
            continue
        kit_root = resolve_kit_path(service, project_root)
        sidecar = kit_root / relpath
        if not parents:
            if sidecar.is_file():
                sidecar.unlink()
                notes.append(f"Removed {name} embed sidecar (no webmail/parent origin configured).")
            continue
        frame_origins = kanidm_origins if name == "kanidm" else parents
        write_sidecar(sidecar, {"frame_ancestors": frame_origins}, header=EMBED_SIDECAR_HEADER)
        if name == "kanidm":
            notes.append(
                f"Allowed Kanidm login to be framed by {', '.join(frame_origins)} ({sidecar})."
            )
        else:
            notes.append(
                f"Allowed {name} to be embedded by {', '.join(frame_origins)} ({sidecar})."
            )
        written += 1

    if written:
        notes.append(
            "Re-apply Kanidm, OpenCloud, Matrix, and Stalwart so they pick up embed "
            "frame-ancestors and the IdP frame-src exception. "
            "On a same-VPS install, bash apply.sh in easydeploy-engine does this."
        )
    elif parents:
        notes.append(
            "Embed parents configured, but OpenCloud/Matrix/Kanidm are not enabled on this engine."
        )
    return notes
