"""Allow Bulwark (and other configured parents) to iframe OpenCloud and Element.

Writes kit integration sidecars:
- OpenCloud: .opencloud-easy-deploy/integration/embed.yaml
- Matrix: .matrix-easy-deploy/integration/embed.yaml

Kits merge those files on apply. Operators can add extra origins in each kit's
deploy.yaml (`embed.frame_ancestors`) or opt out with `embed.managed: false`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from scripts.oidc_wire import (
    read_webmail_domain,
    resolve_kit_path,
    write_sidecar,
)

EMBED_SIDECAR_HEADER = (
    "# Generated by easydeploy-engine. Re-apply the engine after domain changes.\n"
    "# Set embed.managed: false on the kit to ignore this file.\n"
)

PLACEHOLDER_HOSTS = frozenset(
    {
        "webmail.example.com",
        "example.com",
        "mail.example.com",
    }
)

KIT_EMBED_SIDECARS = (
    ("opencloud", ".opencloud-easy-deploy/integration/embed.yaml"),
    ("matrix", ".matrix-easy-deploy/integration/embed.yaml"),
)


def https_origin(value: Any) -> str:
    """Normalize a hostname or URL to `https://host` with no trailing slash."""
    text = str(value or "").strip()
    if not text:
        return ""
    if "://" in text:
        scheme, rest = text.split("://", 1)
        if scheme.lower() not in {"http", "https"}:
            return ""
        host = rest.split("/")[0].split("?")[0].split("#")[0].strip().lower()
    else:
        host = text.split("/")[0].split("?")[0].split("#")[0].strip().lower()
        if host.startswith("*."):
            host = host[2:]
    if not host or host in PLACEHOLDER_HOSTS:
        return ""
    return f"https://{host}"


def unique_https_origins(values: Any) -> list[str]:
    origins: list[str] = []
    seen: set[str] = set()
    if values is None:
        return origins
    if isinstance(values, str):
        values = [values]
    if not isinstance(values, list):
        return origins
    for item in values:
        origin = https_origin(item)
        if origin and origin not in seen:
            seen.add(origin)
            origins.append(origin)
    return origins


def collect_embed_parents(engine_config: dict, enabled: list[dict], project_root: Path) -> list[str]:
    """Parents allowed to iframe OpenCloud/Element (Bulwark webmail, plus extras)."""
    raw: list[Any] = []
    embed = engine_config.get("embed") or {}
    if isinstance(embed, dict):
        raw.extend(embed.get("frame_ancestors") or [])

    by_name = {item["name"]: item for item in enabled}
    identity = engine_config.get("identity") or {}
    consumers = identity.get("consumers") or {}
    if not isinstance(consumers, dict):
        consumers = {}
    stalwart_cfg = consumers.get("stalwart") or {}
    if not isinstance(stalwart_cfg, dict):
        stalwart_cfg = {}

    webmail = str(stalwart_cfg.get("webmail") or stalwart_cfg.get("webmail_domain") or "").strip()
    stalwart = by_name.get("stalwart")
    if stalwart:
        kit_root = resolve_kit_path(stalwart, project_root)
        webmail = webmail or read_webmail_domain(kit_root)
    if webmail:
        raw.append(webmail)

    return unique_https_origins(raw)


def wire_embed(
    engine_config: dict,
    enabled: list[dict],
    project_root: Path,
) -> list[str]:
    """Write embed sidecars so apps can be iframed by Bulwark. Returns status lines."""
    origins = collect_embed_parents(engine_config, enabled, project_root)
    by_name = {item["name"]: item for item in enabled}
    notes: list[str] = []
    written = 0

    for name, relpath in KIT_EMBED_SIDECARS:
        service = by_name.get(name)
        if not service:
            continue
        kit_root = resolve_kit_path(service, project_root)
        sidecar = kit_root / relpath
        if not origins:
            if sidecar.is_file():
                sidecar.unlink()
                notes.append(f"Removed {name} embed sidecar (no webmail/parent origin configured).")
            continue
        write_sidecar(sidecar, {"frame_ancestors": origins}, header=EMBED_SIDECAR_HEADER)
        notes.append(
            f"Allowed {name} to be embedded by {', '.join(origins)} ({sidecar})."
        )
        written += 1

    if written:
        notes.append(
            "Re-apply OpenCloud and Matrix so they pick up embed.frame_ancestors. "
            "On a same-VPS install, bash apply.sh in easydeploy-engine does this."
        )
    elif origins:
        notes.append(
            "Embed parents configured, but OpenCloud/Matrix are not enabled on this engine."
        )
    return notes
