"""Wire Kanidm OIDC/LDAP to local (or declared) consumers without editing operator deploy.yaml.

Writes kit integration sidecars:
- Kanidm: .kanidm-easy-deploy/integration/oidc-clients.d/<id>.yaml
- OpenCloud: .opencloud-easy-deploy/integration/oidc-provider.yaml
- Matrix: .matrix-easy-deploy/integration/oidc-provider.yaml
- Stalwart: .stalwart-easy-deploy/integration/identity-provider.yaml

Kits merge those files on apply. Operators opt out with `oidc.managed: false`
(or `auth.oidc.managed: false` / `features.sso.managed: false` / `identity.managed: false`).
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

import yaml

OPENCLOUD_REDIRECT_PATHS = (
    "/",
    "/web-oidc-callback",
    "/oidc-callback.html",
    "/oidc-silent-redirect.html",
)

SIDECAR_HEADER = (
    "# Generated by easydeploy-engine. Re-apply the engine after domain changes.\n"
    "# Set oidc.managed: false (Kanidm), auth.oidc.managed: false (OpenCloud),\n"
    "# features.sso.managed: false (Matrix), or identity.managed: false (Stalwart) to ignore.\n"
)

_CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
MAS_PATH_PREFIX = "/auth"
KANIDM_SSO_NAME = "Kanidm"
DEFAULT_MATRIX_CLIENT_ID = "matrix"
# OpenCloud's web client requests `groups` as well as `groups_name`. Kanidm
# denies the whole grant if any requested scope is missing from the scope map.
# Role assignment still uses the opencloudRoles claim map (not UUID/SPN groups).
DEFAULT_OIDC_SCOPES = ["openid", "profile", "email", "groups", "groups_name"]
OPENCLOUD_ROLE_CLAIM = "opencloudRoles"


def to_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on"}


def managed_is_false(section: dict | None) -> bool:
    value = (section or {}).get("managed")
    if value is False:
        return True
    return str(value or "").strip().lower() in {"false", "no", "0"}


def load_yaml(path: Path) -> dict:
    with path.open() as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path}: root must be a mapping")
    return data


def write_sidecar(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
    path.write_text(SIDECAR_HEADER + body)


def resolve_kit_path(service: dict, project_root: Path) -> Path:
    base = Path(service["path"]).expanduser()
    if not base.is_absolute():
        base = (project_root / base).resolve()
    return base


def identity_wire_enabled(engine_config: dict) -> bool:
    identity = engine_config.get("identity") or {}
    raw = identity.get("wire", "auto")
    if raw is False or str(raw).strip().lower() in {"false", "no", "0", "off"}:
        return False
    return True


def stable_provider_ulid(name: str, issuer: str) -> str:
    """Must match matrix-easy-deploy/scripts/mas_config.py stable_provider_ulid."""
    digest = hashlib.sha256(f"{name}\0{issuer}".encode()).digest()
    value = int.from_bytes(digest[:16], byteorder="big")
    chars: list[str] = []
    for _ in range(26):
        chars.append(_CROCKFORD[value & 0x1F])
        value >>= 5
    return "".join(reversed(chars))


def kanidm_origin(domain: str) -> str:
    return f"https://{str(domain).strip().rstrip('/')}"


def kanidm_issuer_url(domain: str, client_id: str) -> str:
    return f"{kanidm_origin(domain)}/oauth2/openid/{client_id}"


def ldap_base_dn(domain: str) -> str:
    labels = [part for part in str(domain).strip().lower().split(".") if part]
    if not labels:
        raise ValueError("cannot derive LDAP base DN from an empty domain")
    return ",".join(f"dc={label}" for label in labels)


def matrix_kanidm_provider_id(kanidm_domain: str, client_id: str = DEFAULT_MATRIX_CLIENT_ID) -> str:
    return stable_provider_ulid(KANIDM_SSO_NAME, kanidm_issuer_url(kanidm_domain, client_id))


def matrix_kanidm_redirect_uri(
    matrix_domain: str,
    kanidm_domain: str,
    client_id: str = DEFAULT_MATRIX_CLIENT_ID,
) -> str:
    provider_id = matrix_kanidm_provider_id(kanidm_domain, client_id)
    return f"https://{matrix_domain.rstrip('/')}{MAS_PATH_PREFIX}/upstream/callback/{provider_id}"


def plaintext_oidc_secret(value: str) -> str:
    secret = str(value or "").strip()
    prefix = "$plaintext$"
    if secret.startswith(prefix):
        return secret[len(prefix) :]
    return secret


def load_existing_matrix_secret(matrix_sidecar: Path, kanidm_secret: Path) -> str:
    for path in (matrix_sidecar, kanidm_secret):
        if not path.is_file():
            continue
        data = load_yaml(path)
        secret = plaintext_oidc_secret(str(data.get("client_secret") or ""))
        if secret and not secret.startswith("$"):
            return secret
    return ""


def build_opencloud_client(
    domain: str,
    *,
    client_id: str = "opencloud",
) -> dict[str, Any]:
    origin = f"https://{domain.rstrip('/')}"
    return {
        "client_id": client_id,
        "client_name": "OpenCloud",
        "public": True,
        "prefer_short_username": True,
        "landing_url": origin,
        "redirect_uris": [origin + path if path != "/" else origin + "/" for path in OPENCLOUD_REDIRECT_PATHS],
        "scopes": list(DEFAULT_OIDC_SCOPES),
        "claim_maps": [
            {
                "claim": OPENCLOUD_ROLE_CLAIM,
                "join": "array",
                "mappings": [
                    {"group": "opencloud-admin", "values": ["admin"]},
                    {"group": "opencloud-user", "values": ["user"]},
                    {"group": "opencloud-guest", "values": ["guest"]},
                ],
            }
        ],
    }


def build_opencloud_provider(
    kanidm_domain: str,
    *,
    client_id: str = "opencloud",
) -> dict[str, Any]:
    host = kanidm_domain.strip().rstrip("/")
    return {
        "provider": "kanidm",
        "issuer_url": kanidm_issuer_url(host, client_id),
        "account_url": f"https://{host}/",
        "domain": host,
        "client_id": client_id,
        "client_scopes": " ".join(DEFAULT_OIDC_SCOPES),
        "role_claim": OPENCLOUD_ROLE_CLAIM,
        "role_mapping": {
            "admin": "admin",
            "user": "user",
            "guest": "guest",
        },
    }


def build_matrix_client(
    matrix_domain: str,
    kanidm_domain: str,
    *,
    client_id: str = DEFAULT_MATRIX_CLIENT_ID,
) -> dict[str, Any]:
    origin = f"https://{matrix_domain.rstrip('/')}"
    return {
        "client_id": client_id,
        "client_name": "Matrix",
        "public": False,
        "prefer_short_username": True,
        "landing_url": origin,
        "redirect_uris": [matrix_kanidm_redirect_uri(matrix_domain, kanidm_domain, client_id)],
        "scopes": ["openid", "profile", "email"],
    }


def build_matrix_provider(
    kanidm_domain: str,
    *,
    client_id: str = DEFAULT_MATRIX_CLIENT_ID,
    client_secret: str = "",
) -> dict[str, Any]:
    issuer = kanidm_issuer_url(kanidm_domain, client_id)
    provider = {
        "provider": "kanidm",
        "name": KANIDM_SSO_NAME,
        "issuer": issuer,
        "client_id": client_id,
        "id": matrix_kanidm_provider_id(kanidm_domain, client_id),
        "allow_registration": True,
        "scopes": ["openid", "profile", "email"],
    }
    if client_secret:
        provider["client_secret"] = client_secret
    return provider


def build_stalwart_client(
    mail_hostname: str,
    *,
    client_id: str = "stalwart-webui",
) -> dict[str, Any]:
    origin = f"https://{mail_hostname.rstrip('/')}"
    return {
        "client_id": client_id,
        "client_name": "Stalwart",
        "public": True,
        "prefer_short_username": True,
        "landing_url": origin,
        "redirect_uris": [
            f"{origin}/",
            f"{origin}/login",
            f"{origin}/account/oauth/callback",
            f"{origin}/auth/oidc/callback",
            f"{origin}/admin",
        ],
        "scopes": ["openid", "profile", "email"],
    }


def build_stalwart_identity(
    kanidm_domain: str,
    mail_domain: str,
    *,
    client_id: str = "stalwart-webui",
    ldap_token: str = "",
) -> dict[str, Any]:
    host = kanidm_domain.strip().rstrip("/")
    identity = {
        "provider": "kanidm",
        "domain": host,
        "account_url": f"https://{host}/",
        "oidc": {
            "issuer_url": kanidm_issuer_url(host, client_id),
            "client_id": client_id,
            "claim_username": "preferred_username",
            "username_domain": mail_domain,
            "claim_name": "name",
            "claim_groups": "groups",
            "require_audience": client_id,
        },
        "auth_directory": "oidc",
        "ldap": {
            "url": "ldaps://kanidm:3636",
            "base_dn": ldap_base_dn(host),
            "bind_dn": "dn=token",
            "bind_authentication": True,
            "allow_invalid_certs": True,
            "use_tls": True,
            "filter_login": "(&(objectclass=account)(|(name=?)(mail=?)(spn=?)))",
            "filter_mailbox": "(&(objectclass=account)(|(mail=?)(spn=?)))",
            "attr_email": "mail",
            "attr_description": "displayname",
            "attr_member_of": "memberof",
            "group_class": "group",
        },
    }
    if ldap_token:
        identity["ldap"]["bind_secret"] = ldap_token
    return identity


def read_kanidm_domain(kit_root: Path) -> str:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"Kanidm deploy.yaml not found at {deploy}")
    domain = str((load_yaml(deploy).get("kanidm") or {}).get("domain") or "").strip()
    if not domain or domain == "idm.example.com":
        raise ValueError(f"{deploy}: kanidm.domain is not set")
    return domain


def read_opencloud_domain(kit_root: Path) -> str:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"OpenCloud deploy.yaml not found at {deploy}")
    domain = str((load_yaml(deploy).get("opencloud") or {}).get("domain") or "").strip()
    if not domain or domain == "cloud.example.com":
        raise ValueError(f"{deploy}: opencloud.domain is not set")
    return domain


def read_matrix_domain(kit_root: Path) -> str:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"Matrix deploy.yaml not found at {deploy}")
    domain = str((load_yaml(deploy).get("matrix") or {}).get("domain") or "").strip()
    if not domain or domain == "matrix.example.com":
        raise ValueError(f"{deploy}: matrix.domain is not set")
    return domain


def read_stalwart_domains(kit_root: Path) -> tuple[str, str]:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"Stalwart deploy.yaml not found at {deploy}")
    data = load_yaml(deploy)
    stalwart = data.get("stalwart") or {}
    hostname = str(stalwart.get("hostname") or "").strip()
    domain = str(stalwart.get("domain") or "").strip()
    if not hostname or hostname == "mail.example.com":
        raise ValueError(f"{deploy}: stalwart.hostname is not set")
    if not domain or domain == "example.com":
        raise ValueError(f"{deploy}: stalwart.domain is not set")
    return hostname, domain


def _is_kanidm_sso_provider(provider: Any) -> bool:
    if not isinstance(provider, dict):
        return False
    name = str(provider.get("name") or "").strip().lower()
    client_id = str(provider.get("client_id") or "").strip().lower()
    issuer = str(provider.get("issuer") or "").strip().lower()
    if name in {"kanidm", "authelia"}:
        return True
    if client_id == DEFAULT_MATRIX_CLIENT_ID or client_id.startswith("matrix-"):
        return True
    return "kanidm" in issuer or "/oauth2/openid/" in issuer


def consumer_should_skip(kit_root: Path, service_entry: dict) -> bool:
    if managed_is_false(service_entry.get("oidc") if isinstance(service_entry.get("oidc"), dict) else {}):
        return True
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        return False
    oidc = ((load_yaml(deploy).get("auth") or {}).get("oidc") or {})
    if managed_is_false(oidc):
        return True
    provider = str(oidc.get("provider") or "").strip().lower()
    return bool(provider) and provider not in {"kanidm", "authelia"}


def matrix_should_skip(kit_root: Path, service_entry: dict) -> bool:
    if managed_is_false(service_entry.get("oidc") if isinstance(service_entry.get("oidc"), dict) else {}):
        return True
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        return False
    sso = ((load_yaml(deploy).get("features") or {}).get("sso") or {})
    if not isinstance(sso, dict):
        return False
    if managed_is_false(sso):
        return True
    provider = str(sso.get("provider") or "").strip().lower()
    if provider and provider not in {"kanidm", "authelia"}:
        return True
    providers = sso.get("providers") if isinstance(sso.get("providers"), list) else []
    if providers and not any(_is_kanidm_sso_provider(item) for item in providers):
        if provider not in {"kanidm", "authelia"}:
            return True
    return False


def stalwart_should_skip(kit_root: Path, service_entry: dict) -> bool:
    if managed_is_false(service_entry.get("identity") if isinstance(service_entry.get("identity"), dict) else {}):
        return True
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        return False
    identity = load_yaml(deploy).get("identity") or {}
    if not isinstance(identity, dict):
        return False
    if managed_is_false(identity):
        return True
    provider = str(identity.get("provider") or "").strip().lower()
    return bool(provider) and provider != "kanidm"


def _consumer_cfg(consumers_cfg: dict, name: str) -> dict:
    entry = consumers_cfg.get(name) or {}
    return entry if isinstance(entry, dict) else {}


def _client_id_for(service: dict | None, consumer_cfg: dict, default: str) -> str:
    client_id = default
    if service and isinstance(service.get("oidc"), dict):
        client_id = str(service["oidc"].get("client_id") or "").strip() or client_id
    return str(consumer_cfg.get("client_id") or "").strip() or client_id


def _read_ldap_token(kanidm_root: Path) -> str:
    secrets_path = kanidm_root / ".kanidm-easy-deploy" / "secrets.yaml"
    if not secrets_path.is_file():
        return ""
    data = load_yaml(secrets_path)
    return str(data.get("LDAP_TOKEN") or "").strip()


def wire_identity(
    engine_config: dict,
    enabled: list[dict],
    project_root: Path,
) -> list[str]:
    """Write OIDC/LDAP sidecars. Returns human-readable status lines."""
    if not identity_wire_enabled(engine_config):
        return ["Identity wiring skipped (identity.wire: false)."]

    by_name = {item["name"]: item for item in enabled}
    identity = engine_config.get("identity") or {}
    consumers_cfg = identity.get("consumers") or {}
    if not isinstance(consumers_cfg, dict):
        consumers_cfg = {}

    kanidm = by_name.get("kanidm")
    if not kanidm:
        return ["Identity wiring skipped (Kanidm is not enabled in engine.yaml)."]

    kanidm_root = resolve_kit_path(kanidm, project_root)
    kanidm_domain = str(identity.get("domain") or "").strip() or read_kanidm_domain(kanidm_root)
    clients_dir = kanidm_root / ".kanidm-easy-deploy" / "integration" / "oidc-clients.d"

    notes: list[str] = []
    wired = 0

    opencloud = by_name.get("opencloud")
    opencloud_cfg = _consumer_cfg(consumers_cfg, "opencloud")
    opencloud_domain = str(opencloud_cfg.get("domain") or "").strip()
    opencloud_client_id = _client_id_for(opencloud, opencloud_cfg, "opencloud")

    if opencloud and not consumer_should_skip(resolve_kit_path(opencloud, project_root), opencloud):
        kit_root = resolve_kit_path(opencloud, project_root)
        domain = opencloud_domain or read_opencloud_domain(kit_root)
        client = build_opencloud_client(domain, client_id=opencloud_client_id)
        provider = build_opencloud_provider(kanidm_domain, client_id=opencloud_client_id)
        write_sidecar(clients_dir / f"{opencloud_client_id}.yaml", client)
        write_sidecar(kit_root / ".opencloud-easy-deploy" / "integration" / "oidc-provider.yaml", provider)
        notes.append(f"Wired OpenCloud ({domain}) → Kanidm ({kanidm_domain}) as client {opencloud_client_id!r}.")
        notes.append(f"  Kanidm client definition: {clients_dir / f'{opencloud_client_id}.yaml'}")
        notes.append(f"  OpenCloud provider definition: {kit_root / '.opencloud-easy-deploy' / 'integration' / 'oidc-provider.yaml'}")
        wired += 1
    elif opencloud_domain:
        client = build_opencloud_client(opencloud_domain, client_id=opencloud_client_id)
        write_sidecar(clients_dir / f"{opencloud_client_id}.yaml", client)
        notes.append(
            f"Wired remote OpenCloud ({opencloud_domain}) client {opencloud_client_id!r} into Kanidm "
            f"(split-VPS). Configure OpenCloud auth.oidc on the other host."
        )
        wired += 1
    elif opencloud:
        notes.append("OpenCloud OIDC wiring skipped (auth.oidc.managed: false or non-Kanidm provider).")

    matrix = by_name.get("matrix")
    matrix_cfg = _consumer_cfg(consumers_cfg, "matrix")
    matrix_domain_override = str(matrix_cfg.get("domain") or "").strip()
    matrix_client_id = _client_id_for(matrix, matrix_cfg, DEFAULT_MATRIX_CLIENT_ID)

    if matrix and not matrix_should_skip(resolve_kit_path(matrix, project_root), matrix):
        kit_root = resolve_kit_path(matrix, project_root)
        domain = matrix_domain_override or read_matrix_domain(kit_root)
        matrix_sidecar = kit_root / ".matrix-easy-deploy" / "integration" / "oidc-provider.yaml"
        secret_store = kanidm_root / ".kanidm-easy-deploy" / "integration" / "oidc-secrets.d" / f"{matrix_client_id}.yaml"
        client_secret = load_existing_matrix_secret(matrix_sidecar, secret_store)
        client = build_matrix_client(domain, kanidm_domain, client_id=matrix_client_id)
        provider = build_matrix_provider(
            kanidm_domain, client_id=matrix_client_id, client_secret=client_secret
        )
        write_sidecar(clients_dir / f"{matrix_client_id}.yaml", client)
        write_sidecar(matrix_sidecar, provider)
        notes.append(f"Wired Matrix ({domain}) → Kanidm ({kanidm_domain}) as client {matrix_client_id!r}.")
        wired += 1
    elif matrix_domain_override:
        client = build_matrix_client(matrix_domain_override, kanidm_domain, client_id=matrix_client_id)
        write_sidecar(clients_dir / f"{matrix_client_id}.yaml", client)
        notes.append(
            f"Wired remote Matrix ({matrix_domain_override}) client {matrix_client_id!r} into Kanidm "
            f"(split-VPS). Configure Matrix features.sso on the other host after Kanidm apply writes the secret."
        )
        wired += 1
    elif matrix:
        notes.append("Matrix OIDC wiring skipped (features.sso.managed: false or non-Kanidm provider).")

    stalwart = by_name.get("stalwart")
    stalwart_cfg = _consumer_cfg(consumers_cfg, "stalwart")
    stalwart_host_override = str(stalwart_cfg.get("hostname") or stalwart_cfg.get("domain") or "").strip()
    stalwart_mail_domain = str(stalwart_cfg.get("mail_domain") or "").strip()
    stalwart_client_id = _client_id_for(stalwart, stalwart_cfg, "stalwart-webui")

    if stalwart and not stalwart_should_skip(resolve_kit_path(stalwart, project_root), stalwart):
        kit_root = resolve_kit_path(stalwart, project_root)
        hostname, mail_domain = read_stalwart_domains(kit_root)
        hostname = stalwart_host_override or hostname
        mail_domain = stalwart_mail_domain or mail_domain
        client = build_stalwart_client(hostname, client_id=stalwart_client_id)
        identity_sidecar = build_stalwart_identity(
            kanidm_domain,
            mail_domain,
            client_id=stalwart_client_id,
            ldap_token=_read_ldap_token(kanidm_root),
        )
        write_sidecar(clients_dir / f"{stalwart_client_id}.yaml", client)
        stale_client = clients_dir / "stalwart.yaml"
        if stalwart_client_id != "stalwart" and stale_client.is_file():
            stale_client.unlink()
        write_sidecar(kit_root / ".stalwart-easy-deploy" / "integration" / "identity-provider.yaml", identity_sidecar)
        notes.append(
            f"Wired Stalwart ({hostname}) → Kanidm LDAP + OIDC ({kanidm_domain}) as client {stalwart_client_id!r}."
        )
        wired += 1
    elif stalwart_host_override:
        client = build_stalwart_client(stalwart_host_override, client_id=stalwart_client_id)
        write_sidecar(clients_dir / f"{stalwart_client_id}.yaml", client)
        notes.append(
            f"Wired remote Stalwart ({stalwart_host_override}) client {stalwart_client_id!r} into Kanidm "
            f"(split-VPS). Configure Stalwart identity on the other host."
        )
        wired += 1
    elif stalwart:
        notes.append("Stalwart identity wiring skipped (identity.managed: false or non-Kanidm provider).")

    if wired == 0 and not notes:
        notes.append(
            "Identity wiring: no consumers enabled (OpenCloud/Matrix/Stalwart) and no identity.consumers.domain set."
        )
    if wired:
        notes.append(
            "Re-run apply.sh in kanidm-easy-deploy, then each app kit, so they pick up the sidecars. "
            "On a same-VPS install, bash wizard.sh in easydeploy-engine handles this order."
        )
    return notes
