"""Wire Authelia OIDC to local (or declared) consumers without editing operator deploy.yaml.

Writes kit integration sidecars:
- Authelia: .authelia-easy-deploy/integration/oidc-clients.d/<id>.yaml
- OpenCloud: .opencloud-easy-deploy/integration/oidc-provider.yaml
- Matrix: .matrix-easy-deploy/integration/oidc-provider.yaml

Kits merge those files on apply. Operators opt out with `oidc.managed: false`
(or `auth.oidc.managed: false` / `features.sso.managed: false`).
"""

from __future__ import annotations

import hashlib
import secrets
from pathlib import Path
from typing import Any

import yaml

OPENCLOUD_REDIRECT_PATHS = (
    "/",
    "/web-oidc-callback",
    "/oidc-callback.html",
    "/oidc-silent-redirect.html",
)

SIDECAR_HEADER = (
    "# Generated by easydeploy-engine. Re-apply the engine after domain changes.\n"
    "# Set oidc.managed: false (Authelia), auth.oidc.managed: false (OpenCloud),\n"
    "# or features.sso.managed: false (Matrix) to ignore.\n"
)

_CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
MAS_PATH_PREFIX = "/auth"
AUTHELIA_SSO_NAME = "Authelia"
DEFAULT_MATRIX_CLIENT_ID = "matrix"


def to_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on"}


def managed_is_false(section: dict | None) -> bool:
    value = (section or {}).get("managed")
    if value is False:
        return True
    return str(value or "").strip().lower() in {"false", "no", "0"}


def load_yaml(path: Path) -> dict:
    with path.open() as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path}: root must be a mapping")
    return data


def write_sidecar(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
    path.write_text(SIDECAR_HEADER + body)


def resolve_kit_path(service: dict, project_root: Path) -> Path:
    base = Path(service["path"]).expanduser()
    if not base.is_absolute():
        base = (project_root / base).resolve()
    return base


def identity_wire_enabled(engine_config: dict) -> bool:
    identity = engine_config.get("identity") or {}
    raw = identity.get("wire", "auto")
    if raw is False or str(raw).strip().lower() in {"false", "no", "0", "off"}:
        return False
    return True


def stable_provider_ulid(name: str, issuer: str) -> str:
    """Must match matrix-easy-deploy/scripts/mas_config.py stable_provider_ulid."""
    digest = hashlib.sha256(f"{name}\0{issuer}".encode()).digest()
    value = int.from_bytes(digest[:16], byteorder="big")
    chars: list[str] = []
    for _ in range(26):
        chars.append(_CROCKFORD[value & 0x1F])
        value >>= 5
    return "".join(reversed(chars))


def authelia_issuer_url(authelia_domain: str) -> str:
    return f"https://{str(authelia_domain).strip().rstrip('/')}"


def matrix_authelia_provider_id(authelia_domain: str) -> str:
    return stable_provider_ulid(AUTHELIA_SSO_NAME, authelia_issuer_url(authelia_domain))


def matrix_authelia_redirect_uri(matrix_domain: str, authelia_domain: str) -> str:
    provider_id = matrix_authelia_provider_id(authelia_domain)
    return f"https://{matrix_domain.rstrip('/')}{MAS_PATH_PREFIX}/upstream/callback/{provider_id}"


def plaintext_oidc_secret(value: str) -> str:
    secret = str(value or "").strip()
    prefix = "$plaintext$"
    if secret.startswith(prefix):
        return secret[len(prefix) :]
    return secret


def authelia_client_secret_digest(secret: str) -> str:
    digest = str(secret or "").strip()
    if digest.startswith("$"):
        return digest
    return f"$plaintext${digest}"


def load_or_create_matrix_oidc_secret(matrix_sidecar: Path, authelia_sidecar: Path) -> str:
    if matrix_sidecar.is_file():
        data = load_yaml(matrix_sidecar)
        secret = plaintext_oidc_secret(str(data.get("client_secret") or ""))
        if secret and not secret.startswith("$"):
            return secret
    if authelia_sidecar.is_file():
        data = load_yaml(authelia_sidecar)
        secret = plaintext_oidc_secret(str(data.get("client_secret") or ""))
        if secret and not secret.startswith("$"):
            return secret
    return secrets.token_urlsafe(32)


def build_opencloud_client(
    domain: str,
    *,
    client_id: str = "opencloud",
    authorization_policy: str = "two_factor",
) -> dict[str, Any]:
    origin = f"https://{domain.rstrip('/')}"
    return {
        "client_id": client_id,
        "client_name": "OpenCloud",
        "claims_policy": "opencloud",
        "public": True,
        "authorization_policy": authorization_policy,
        "require_pkce": True,
        "pkce_challenge_method": "S256",
        "token_endpoint_auth_method": "none",
        "redirect_uris": [origin + path if path != "/" else origin + "/" for path in OPENCLOUD_REDIRECT_PATHS],
        "scopes": ["openid", "offline_access", "groups", "profile", "email"],
        "grant_types": ["authorization_code", "refresh_token"],
        "response_types": ["code"],
    }


def build_opencloud_provider(
    authelia_domain: str,
    *,
    client_id: str = "opencloud",
) -> dict[str, Any]:
    host = authelia_domain.strip().rstrip("/")
    return {
        "provider": "authelia",
        "issuer_url": f"https://{host}",
        "account_url": f"https://{host}/",
        "domain": host,
        "client_id": client_id,
        "client_scopes": "openid profile email groups",
        "role_claim": "groups",
        "role_mapping": {
            "admin": "opencloud-admin",
            "user": "opencloud-user",
            "guest": "opencloud-guest",
        },
    }


def build_matrix_client(
    matrix_domain: str,
    authelia_domain: str,
    *,
    client_id: str = DEFAULT_MATRIX_CLIENT_ID,
    client_secret: str,
    authorization_policy: str = "two_factor",
) -> dict[str, Any]:
    return {
        "client_id": client_id,
        "client_name": "Matrix",
        "claims_policy": "matrix",
        "public": False,
        "authorization_policy": authorization_policy,
        "require_pkce": False,
        "token_endpoint_auth_method": "client_secret_basic",
        "client_secret": authelia_client_secret_digest(client_secret),
        "redirect_uris": [matrix_authelia_redirect_uri(matrix_domain, authelia_domain)],
        "scopes": ["openid", "profile", "email"],
        "grant_types": ["authorization_code", "refresh_token"],
        "response_types": ["code"],
    }


def build_matrix_provider(
    authelia_domain: str,
    *,
    client_id: str = DEFAULT_MATRIX_CLIENT_ID,
    client_secret: str,
) -> dict[str, Any]:
    issuer = authelia_issuer_url(authelia_domain)
    return {
        "provider": "authelia",
        "name": AUTHELIA_SSO_NAME,
        "issuer": issuer,
        "client_id": client_id,
        "client_secret": client_secret,
        "id": matrix_authelia_provider_id(authelia_domain),
        "allow_registration": True,
        "scopes": ["openid", "profile", "email"],
    }


def read_authelia_domain(kit_root: Path) -> str:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"Authelia deploy.yaml not found at {deploy}")
    domain = str((load_yaml(deploy).get("authelia") or {}).get("domain") or "").strip()
    if not domain or domain == "auth.example.com":
        raise ValueError(f"{deploy}: authelia.domain is not set")
    return domain


def read_opencloud_domain(kit_root: Path) -> str:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"OpenCloud deploy.yaml not found at {deploy}")
    domain = str((load_yaml(deploy).get("opencloud") or {}).get("domain") or "").strip()
    if not domain or domain == "cloud.example.com":
        raise ValueError(f"{deploy}: opencloud.domain is not set")
    return domain


def read_matrix_domain(kit_root: Path) -> str:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"Matrix deploy.yaml not found at {deploy}")
    domain = str((load_yaml(deploy).get("matrix") or {}).get("domain") or "").strip()
    if not domain or domain == "matrix.example.com":
        raise ValueError(f"{deploy}: matrix.domain is not set")
    return domain


def _is_authelia_sso_provider(provider: Any) -> bool:
    if not isinstance(provider, dict):
        return False
    name = str(provider.get("name") or "").strip().lower()
    client_id = str(provider.get("client_id") or "").strip().lower()
    issuer = str(provider.get("issuer") or "").strip().lower()
    if name == "authelia":
        return True
    if client_id == DEFAULT_MATRIX_CLIENT_ID or client_id.startswith("matrix-"):
        return True
    return "authelia" in issuer


def consumer_should_skip(kit_root: Path, service_entry: dict) -> bool:
    if managed_is_false(service_entry.get("oidc") if isinstance(service_entry.get("oidc"), dict) else {}):
        return True
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        return False
    oidc = ((load_yaml(deploy).get("auth") or {}).get("oidc") or {})
    if managed_is_false(oidc):
        return True
    provider = str(oidc.get("provider") or "").strip().lower()
    return bool(provider) and provider != "authelia"


def matrix_should_skip(kit_root: Path, service_entry: dict) -> bool:
    if managed_is_false(service_entry.get("oidc") if isinstance(service_entry.get("oidc"), dict) else {}):
        return True
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        return False
    sso = ((load_yaml(deploy).get("features") or {}).get("sso") or {})
    if not isinstance(sso, dict):
        return False
    if managed_is_false(sso):
        return True
    provider = str(sso.get("provider") or "").strip().lower()
    if provider and provider != "authelia":
        return True
    providers = sso.get("providers") if isinstance(sso.get("providers"), list) else []
    if providers and not any(_is_authelia_sso_provider(item) for item in providers) and provider != "authelia":
        return True
    return False


def _consumer_cfg(consumers_cfg: dict, name: str) -> dict:
    entry = consumers_cfg.get(name) or {}
    return entry if isinstance(entry, dict) else {}


def _client_id_for(service: dict | None, consumer_cfg: dict, default: str) -> str:
    client_id = default
    if service and isinstance(service.get("oidc"), dict):
        client_id = str(service["oidc"].get("client_id") or "").strip() or client_id
    return str(consumer_cfg.get("client_id") or "").strip() or client_id


def wire_identity(
    engine_config: dict,
    enabled: list[dict],
    project_root: Path,
) -> list[str]:
    """Write OIDC sidecars. Returns human-readable status lines."""
    if not identity_wire_enabled(engine_config):
        return ["OIDC wiring skipped (identity.wire: false)."]

    by_name = {item["name"]: item for item in enabled}
    identity = engine_config.get("identity") or {}
    consumers_cfg = identity.get("consumers") or {}
    if not isinstance(consumers_cfg, dict):
        consumers_cfg = {}

    authelia = by_name.get("authelia")
    if not authelia:
        return ["OIDC wiring skipped (Authelia is not enabled in engine.yaml)."]

    authelia_root = resolve_kit_path(authelia, project_root)
    authelia_domain = str(identity.get("domain") or "").strip() or read_authelia_domain(authelia_root)
    policy = str(identity.get("authorization_policy") or "two_factor").strip() or "two_factor"

    notes: list[str] = []
    wired = 0

    opencloud = by_name.get("opencloud")
    opencloud_cfg = _consumer_cfg(consumers_cfg, "opencloud")
    opencloud_domain = str(opencloud_cfg.get("domain") or "").strip()
    opencloud_client_id = _client_id_for(opencloud, opencloud_cfg, "opencloud")

    if opencloud and not consumer_should_skip(resolve_kit_path(opencloud, project_root), opencloud):
        kit_root = resolve_kit_path(opencloud, project_root)
        domain = opencloud_domain or read_opencloud_domain(kit_root)
        client = build_opencloud_client(domain, client_id=opencloud_client_id, authorization_policy=policy)
        provider = build_opencloud_provider(authelia_domain, client_id=opencloud_client_id)
        write_sidecar(
            authelia_root / ".authelia-easy-deploy" / "integration" / "oidc-clients.d" / f"{opencloud_client_id}.yaml",
            client,
        )
        write_sidecar(kit_root / ".opencloud-easy-deploy" / "integration" / "oidc-provider.yaml", provider)
        notes.append(f"Wired OpenCloud ({domain}) → Authelia ({authelia_domain}) as client {opencloud_client_id!r}.")
        wired += 1
    elif opencloud_domain:
        client = build_opencloud_client(
            opencloud_domain, client_id=opencloud_client_id, authorization_policy=policy
        )
        write_sidecar(
            authelia_root / ".authelia-easy-deploy" / "integration" / "oidc-clients.d" / f"{opencloud_client_id}.yaml",
            client,
        )
        notes.append(
            f"Wired remote OpenCloud ({opencloud_domain}) client {opencloud_client_id!r} into Authelia "
            f"(split-VPS). Configure OpenCloud auth.oidc on the other host."
        )
        wired += 1
    elif opencloud:
        notes.append("OpenCloud OIDC wiring skipped (auth.oidc.managed: false or non-Authelia provider).")

    matrix = by_name.get("matrix")
    matrix_cfg = _consumer_cfg(consumers_cfg, "matrix")
    matrix_domain_override = str(matrix_cfg.get("domain") or "").strip()
    matrix_client_id = _client_id_for(matrix, matrix_cfg, DEFAULT_MATRIX_CLIENT_ID)

    if matrix and not matrix_should_skip(resolve_kit_path(matrix, project_root), matrix):
        kit_root = resolve_kit_path(matrix, project_root)
        domain = matrix_domain_override or read_matrix_domain(kit_root)
        matrix_sidecar = kit_root / ".matrix-easy-deploy" / "integration" / "oidc-provider.yaml"
        authelia_sidecar = (
            authelia_root / ".authelia-easy-deploy" / "integration" / "oidc-clients.d" / f"{matrix_client_id}.yaml"
        )
        client_secret = load_or_create_matrix_oidc_secret(matrix_sidecar, authelia_sidecar)
        client = build_matrix_client(
            domain,
            authelia_domain,
            client_id=matrix_client_id,
            client_secret=client_secret,
            authorization_policy=policy,
        )
        provider = build_matrix_provider(
            authelia_domain, client_id=matrix_client_id, client_secret=client_secret
        )
        write_sidecar(authelia_sidecar, client)
        write_sidecar(matrix_sidecar, provider)
        notes.append(f"Wired Matrix ({domain}) → Authelia ({authelia_domain}) as client {matrix_client_id!r}.")
        wired += 1
    elif matrix_domain_override:
        secret_store = authelia_root / ".authelia-easy-deploy" / "integration" / "matrix-oidc-secret.yaml"
        authelia_sidecar = (
            authelia_root / ".authelia-easy-deploy" / "integration" / "oidc-clients.d" / f"{matrix_client_id}.yaml"
        )
        client_secret = load_or_create_matrix_oidc_secret(secret_store, authelia_sidecar)
        write_sidecar(secret_store, {"client_secret": client_secret})
        client = build_matrix_client(
            matrix_domain_override,
            authelia_domain,
            client_id=matrix_client_id,
            client_secret=client_secret,
            authorization_policy=policy,
        )
        write_sidecar(authelia_sidecar, client)
        notes.append(
            f"Wired remote Matrix ({matrix_domain_override}) client {matrix_client_id!r} into Authelia "
            f"(split-VPS). Configure Matrix features.sso on the other host; client secret is in "
            f"{secret_store}."
        )
        wired += 1
    elif matrix:
        notes.append("Matrix OIDC wiring skipped (features.sso.managed: false or non-Authelia provider).")

    if wired == 0 and not notes:
        notes.append(
            "OIDC wiring: no consumers enabled (OpenCloud/Matrix) and no identity.consumers.domain set."
        )
    if wired:
        notes.append(
            "Re-run apply.sh in authelia-easy-deploy, then each app kit, so they pick up the sidecars. "
            "On a same-VPS install, bash wizard.sh in easydeploy-engine handles this order."
        )
    return notes
