"""Wire Authelia OIDC to local (or declared) consumers without editing operator deploy.yaml.

Writes kit integration sidecars:
- Authelia: .authelia-easy-deploy/integration/oidc-clients.d/<id>.yaml
- OpenCloud: .opencloud-easy-deploy/integration/oidc-provider.yaml

Kits merge those files on apply. Operators opt out with `oidc.managed: false`
(or `auth.oidc.managed: false` / `services.<name>.oidc.managed: false`).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

OPENCLOUD_REDIRECT_PATHS = (
    "/",
    "/web-oidc-callback",
    "/oidc-callback.html",
    "/oidc-silent-redirect.html",
)

SIDECAR_HEADER = (
    "# Generated by easydeploy-engine. Re-apply the engine after domain changes.\n"
    "# Set oidc.managed: false (Authelia) or auth.oidc.managed: false (OpenCloud) to ignore.\n"
)


def to_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on"}


def managed_is_false(section: dict | None) -> bool:
    value = (section or {}).get("managed")
    if value is False:
        return True
    return str(value or "").strip().lower() in {"false", "no", "0"}


def load_yaml(path: Path) -> dict:
    with path.open() as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path}: root must be a mapping")
    return data


def write_sidecar(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
    path.write_text(SIDECAR_HEADER + body)


def resolve_kit_path(service: dict, project_root: Path) -> Path:
    base = Path(service["path"]).expanduser()
    if not base.is_absolute():
        base = (project_root / base).resolve()
    return base


def identity_wire_enabled(engine_config: dict) -> bool:
    identity = engine_config.get("identity") or {}
    raw = identity.get("wire", "auto")
    if raw is False or str(raw).strip().lower() in {"false", "no", "0", "off"}:
        return False
    return True


def build_opencloud_client(
    domain: str,
    *,
    client_id: str = "opencloud",
    authorization_policy: str = "two_factor",
) -> dict[str, Any]:
    origin = f"https://{domain.rstrip('/')}"
    return {
        "client_id": client_id,
        "client_name": "OpenCloud",
        "claims_policy": "opencloud",
        "public": True,
        "authorization_policy": authorization_policy,
        "require_pkce": True,
        "pkce_challenge_method": "S256",
        "token_endpoint_auth_method": "none",
        "redirect_uris": [origin + path if path != "/" else origin + "/" for path in OPENCLOUD_REDIRECT_PATHS],
        "scopes": ["openid", "offline_access", "groups", "profile", "email"],
        "grant_types": ["authorization_code", "refresh_token"],
        "response_types": ["code"],
    }


def build_opencloud_provider(
    authelia_domain: str,
    *,
    client_id: str = "opencloud",
) -> dict[str, Any]:
    host = authelia_domain.strip().rstrip("/")
    return {
        "provider": "authelia",
        "issuer_url": f"https://{host}",
        "account_url": f"https://{host}/",
        "domain": host,
        "client_id": client_id,
        "client_scopes": "openid profile email groups",
        "role_claim": "groups",
        "role_mapping": {
            "admin": "opencloud-admin",
            "user": "opencloud-user",
            "guest": "opencloud-guest",
        },
    }


def read_authelia_domain(kit_root: Path) -> str:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"Authelia deploy.yaml not found at {deploy}")
    domain = str((load_yaml(deploy).get("authelia") or {}).get("domain") or "").strip()
    if not domain or domain == "auth.example.com":
        raise ValueError(f"{deploy}: authelia.domain is not set")
    return domain


def read_opencloud_domain(kit_root: Path) -> str:
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        raise FileNotFoundError(f"OpenCloud deploy.yaml not found at {deploy}")
    domain = str((load_yaml(deploy).get("opencloud") or {}).get("domain") or "").strip()
    if not domain or domain == "cloud.example.com":
        raise ValueError(f"{deploy}: opencloud.domain is not set")
    return domain


def consumer_should_skip(kit_root: Path, service_entry: dict) -> bool:
    if managed_is_false(service_entry.get("oidc") if isinstance(service_entry.get("oidc"), dict) else {}):
        return True
    deploy = kit_root / "deploy.yaml"
    if not deploy.is_file():
        return False
    oidc = ((load_yaml(deploy).get("auth") or {}).get("oidc") or {})
    if managed_is_false(oidc):
        return True
    provider = str(oidc.get("provider") or "").strip().lower()
    return bool(provider) and provider != "authelia"


def wire_identity(
    engine_config: dict,
    enabled: list[dict],
    project_root: Path,
) -> list[str]:
    """Write OIDC sidecars. Returns human-readable status lines."""
    if not identity_wire_enabled(engine_config):
        return ["OIDC wiring skipped (identity.wire: false)."]

    by_name = {item["name"]: item for item in enabled}
    identity = engine_config.get("identity") or {}
    consumers_cfg = identity.get("consumers") or {}
    if not isinstance(consumers_cfg, dict):
        consumers_cfg = {}

    authelia = by_name.get("authelia")
    if not authelia:
        return ["OIDC wiring skipped (Authelia is not enabled in engine.yaml)."]

    authelia_root = resolve_kit_path(authelia, project_root)
    authelia_domain = str(identity.get("domain") or "").strip() or read_authelia_domain(authelia_root)
    policy = str(identity.get("authorization_policy") or "two_factor").strip() or "two_factor"

    notes: list[str] = []
    wired = 0

    opencloud = by_name.get("opencloud")
    opencloud_cfg = consumers_cfg.get("opencloud") or {}
    if not isinstance(opencloud_cfg, dict):
        opencloud_cfg = {}
    opencloud_domain = str(opencloud_cfg.get("domain") or "").strip()

    client_id = "opencloud"
    if opencloud and isinstance(opencloud.get("oidc"), dict):
        client_id = str(opencloud["oidc"].get("client_id") or "").strip() or client_id
    client_id = str(opencloud_cfg.get("client_id") or "").strip() or client_id

    if opencloud and not consumer_should_skip(resolve_kit_path(opencloud, project_root), opencloud):
        kit_root = resolve_kit_path(opencloud, project_root)
        domain = opencloud_domain or read_opencloud_domain(kit_root)
        client = build_opencloud_client(domain, client_id=client_id, authorization_policy=policy)
        provider = build_opencloud_provider(authelia_domain, client_id=client_id)
        write_sidecar(
            authelia_root / ".authelia-easy-deploy" / "integration" / "oidc-clients.d" / f"{client_id}.yaml",
            client,
        )
        write_sidecar(kit_root / ".opencloud-easy-deploy" / "integration" / "oidc-provider.yaml", provider)
        notes.append(f"Wired OpenCloud ({domain}) → Authelia ({authelia_domain}) as client {client_id!r}.")
        wired += 1
    elif opencloud_domain:
        client = build_opencloud_client(
            opencloud_domain, client_id=client_id, authorization_policy=policy
        )
        write_sidecar(
            authelia_root / ".authelia-easy-deploy" / "integration" / "oidc-clients.d" / f"{client_id}.yaml",
            client,
        )
        notes.append(
            f"Wired remote OpenCloud ({opencloud_domain}) client {client_id!r} into Authelia "
            f"(split-VPS). Configure OpenCloud auth.oidc on the other host."
        )
        wired += 1
    elif opencloud:
        notes.append("OpenCloud OIDC wiring skipped (auth.oidc.managed: false or non-Authelia provider).")

    if wired == 0 and not notes:
        notes.append("OIDC wiring: no consumers enabled (OpenCloud) and no identity.consumers.domain set.")
    if wired:
        notes.append(
            "Re-run apply.sh in authelia-easy-deploy, then opencloud-easy-deploy, so they pick up the sidecars. "
            "On a same-VPS install, bash wizard.sh in easydeploy-engine handles this order."
        )
    return notes
